e:
	#compiles and runs ex1.c, then deletes executable files after
	cc ex1.c -o ex1
	./ex1	
	rm -f ex1

debug:
	#compiles, with verbose printing, executes function, and deletes executable file afterwards
	cc -Wall -g ex1.c -o ex1
	./ex1	
	rm -f ex1

clean:
	#deletes executable binary of the file ./ex1
	rm -f ex1
